# Site settings
title: Michael Wadman
SEOTitle: Michael Wadman | Network Engineer
header-img: img/website-header.jpg
email: michael.wadman@gmail.com
description: "My thoughts and experiences with all things network"
keyword: "Michael Wadman, Network, Network Engineering"
url: "https://mwadman.github.io" # Your host, for absolute URL
baseurl: "" # For example, '/blog' if your blog hosted on 'host/blog'
theme_github_repo: "https://github.com/qiubaiying/qiubaiying.github.io" # Also look at https://github.com/Huxpro/huxpro.github.io

# Sidebar settings
sidebar: False # Whether or not using Sidebar. TODO: Change this?
sidebar-about-description: "Network Engineer in New Zealand. Opinions are my own."
sidebar-avatar: /img/favicon.png # Use an absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: true

# Social Media
github_username: mwadman
# facebook_username: example
# twitter_username: example


# Build settings
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true # If you want to customize anchor. check out line:181 of `post.html`


# Gems
## from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# Documentation: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
# Since 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
kramdown:
  input: GFM  # Use Github Flavored Markdown

# Comments
## Gitalk
gitalk:
  enable: false #Enables Gitalk Comments
  clientID:  # Generated clientID
  clientSecret: # Generated clientSecret
  repo: mwadman.github.io # Repository Name
  owner: mwadman    # Github Username
  admin: mwadman
  distractionFreeMode: true # Enables Shadow Mask like Facebook

# Featured Tags
featured-tags: false # Shows features tags on the front page
featured-condition-size: 1 # Threshold for tags appearing


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
